/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Vista.java
 *
 * Created on 10/10/2012, 07:44:04 PM
 */
package Vista;

import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.*;
import java.util.logging.*;
import javax.swing.*;
import jsyntaxpane.DefaultSyntaxKit;

/**
 *
 * @author Antonio
 */
public class Vista extends javax.swing.JFrame {

    
    
    /** Creates new form Vista */
    public Vista() {
        initComponents();
        linea=new NumeroLinea(this.areaPrincipal);
        this.jScrollPane2.setRowHeaderView(linea);
        archivo = new Archivo();
        this.setTitle("Nuevo" );
        jsyntaxpane.DefaultSyntaxKit.initKit();
        areaPrincipal.setContentType("text/java");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        NuevoBoton = new javax.swing.JButton();
        AbrirBoton = new javax.swing.JButton();
        GuardarBoton = new javax.swing.JButton();
        GuardarComoBoton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        DeshacerBoton = new javax.swing.JButton();
        RehacerBoton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        CompilarBoton = new javax.swing.JButton();
        EjecutarBoton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        CortarBoton = new javax.swing.JButton();
        CopiarBoton = new javax.swing.JButton();
        PegarBoton = new javax.swing.JButton();
        SeleccionarBoton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        BuscarBoton = new javax.swing.JButton();
        ReemplazarBoton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaPrincipal = new javax.swing.JEditorPane();
        panelTab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alexico = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        arbolSintactico = new javax.swing.JTree();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaCodigoP = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        arbolSemantico = new javax.swing.JTree();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaPanel = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        errores = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        MArchivo = new javax.swing.JMenu();
        archivoAbrir = new javax.swing.JMenuItem();
        archivoGuardar = new javax.swing.JMenuItem();
        archivoGuardarComo = new javax.swing.JMenuItem();
        archivoCerrar = new javax.swing.JMenuItem();
        archivoSalir = new javax.swing.JMenuItem();
        MEdicion = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        MCompilar = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        MAyuda = new javax.swing.JMenu();
        tutorial = new javax.swing.JMenuItem();
        acercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 43, 38));

        jToolBar1.setRollover(true);

        NuevoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_new.png"))); // NOI18N
        NuevoBoton.setFocusable(false);
        NuevoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NuevoBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        NuevoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(NuevoBoton);

        AbrirBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_open.png"))); // NOI18N
        AbrirBoton.setFocusable(false);
        AbrirBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AbrirBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AbrirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(AbrirBoton);

        GuardarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_save.png"))); // NOI18N
        GuardarBoton.setFocusable(false);
        GuardarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GuardarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GuardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(GuardarBoton);

        GuardarComoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_saveas.png"))); // NOI18N
        GuardarComoBoton.setFocusable(false);
        GuardarComoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GuardarComoBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GuardarComoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarComoBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(GuardarComoBoton);
        jToolBar1.add(jSeparator1);

        DeshacerBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_undo.png"))); // NOI18N
        DeshacerBoton.setFocusable(false);
        DeshacerBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DeshacerBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        DeshacerBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeshacerBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(DeshacerBoton);

        RehacerBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_redo.png"))); // NOI18N
        RehacerBoton.setFocusable(false);
        RehacerBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RehacerBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RehacerBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RehacerBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(RehacerBoton);
        jToolBar1.add(jSeparator2);

        CompilarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_compile.png"))); // NOI18N
        CompilarBoton.setFocusable(false);
        CompilarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CompilarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(CompilarBoton);

        EjecutarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_run.png"))); // NOI18N
        EjecutarBoton.setFocusable(false);
        EjecutarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EjecutarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EjecutarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(EjecutarBoton);
        jToolBar1.add(jSeparator3);

        CortarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_cut.png"))); // NOI18N
        CortarBoton.setFocusable(false);
        CortarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CortarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CortarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CortarBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(CortarBoton);

        CopiarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_copy.png"))); // NOI18N
        CopiarBoton.setFocusable(false);
        CopiarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CopiarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CopiarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopiarBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(CopiarBoton);

        PegarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_paste.png"))); // NOI18N
        PegarBoton.setFocusable(false);
        PegarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PegarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PegarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PegarBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(PegarBoton);

        SeleccionarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_select.png"))); // NOI18N
        SeleccionarBoton.setFocusable(false);
        SeleccionarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SeleccionarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SeleccionarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(SeleccionarBoton);
        jToolBar1.add(jSeparator4);

        BuscarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_search.png"))); // NOI18N
        BuscarBoton.setFocusable(false);
        BuscarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BuscarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BuscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(BuscarBoton);

        ReemplazarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesToolbar/tp_replace.png"))); // NOI18N
        ReemplazarBoton.setFocusable(false);
        ReemplazarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ReemplazarBoton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ReemplazarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReemplazarBotonActionPerformed(evt);
            }
        });
        jToolBar1.add(ReemplazarBoton);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        areaPrincipal.setName("areaPrincipal"); // NOI18N
        jScrollPane2.setViewportView(areaPrincipal);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        panelTab.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        panelTab.setName(""); // NOI18N

        Alexico.setColumns(20);
        Alexico.setRows(5);
        jScrollPane1.setViewportView(Alexico);

        panelTab.addTab("Léxico", jScrollPane1);

        jScrollPane6.setViewportView(arbolSintactico);

        panelTab.addTab("Árbol Sintáctico", jScrollPane6);

        areaCodigoP.setColumns(20);
        areaCodigoP.setRows(5);
        jScrollPane5.setViewportView(areaCodigoP);

        panelTab.addTab("Código P", jScrollPane5);

        jScrollPane3.setViewportView(arbolSemantico);

        panelTab.addTab("Árbol semantico", jScrollPane3);

        tablaPanel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tablaPanel);

        panelTab.addTab("Tabla de símbolos", jScrollPane7);

        errores.setColumns(20);
        errores.setRows(5);
        jScrollPane4.setViewportView(errores);

        jTabbedPane2.addTab("Errores", jScrollPane4);

        jMenuBar1.setBackground(new java.awt.Color(51, 43, 38));

        MArchivo.setText("Archivo");

        archivoAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        archivoAbrir.setText("Abrir");
        archivoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoAbrirActionPerformed(evt);
            }
        });
        MArchivo.add(archivoAbrir);

        archivoGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        archivoGuardar.setText("Guardar");
        archivoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoGuardarActionPerformed(evt);
            }
        });
        MArchivo.add(archivoGuardar);

        archivoGuardarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        archivoGuardarComo.setText("Guardar como...");
        archivoGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoGuardarComoActionPerformed(evt);
            }
        });
        MArchivo.add(archivoGuardarComo);

        archivoCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        archivoCerrar.setText("Nuevo");
        archivoCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoCerrarActionPerformed(evt);
            }
        });
        MArchivo.add(archivoCerrar);

        archivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        archivoSalir.setText("Salir");
        archivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoSalirActionPerformed(evt);
            }
        });
        MArchivo.add(archivoSalir);

        jMenuBar1.add(MArchivo);

        MEdicion.setText("Edición");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Deshacer");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        MEdicion.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Rehacer");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        MEdicion.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Cortar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        MEdicion.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Copiar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        MEdicion.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Pegar");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        MEdicion.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Seleccionar todo");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        MEdicion.add(jMenuItem11);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Buscar");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        MEdicion.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setText("Reemplazar");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        MEdicion.add(jMenuItem13);

        jMenuBar1.add(MEdicion);

        MCompilar.setText("Compilar");

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem14.setText("Compilar");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        MCompilar.add(jMenuItem14);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem15.setText("Ejecutar");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        MCompilar.add(jMenuItem15);

        jMenuBar1.add(MCompilar);

        MAyuda.setBackground(new java.awt.Color(51, 43, 38));
        MAyuda.setText("Ayuda");

        tutorial.setText("Tutorial");
        tutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialActionPerformed(evt);
            }
        });
        MAyuda.add(tutorial);

        acercaDe.setText("Acerca de...");
        acercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDeActionPerformed(evt);
            }
        });
        MAyuda.add(acercaDe);

        jMenuBar1.add(MAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTabbedPane2))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelTab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelTab))
                .addContainerGap())
        );

        panelTab.getAccessibleContext().setAccessibleName("Lexico");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void AbrirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirBotonActionPerformed

    JTextArea texto = archivo.abrir(this);
    try {
            areaPrincipal.setText(texto.getText());
        } catch (Exception ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }

}//GEN-LAST:event_AbrirBotonActionPerformed

private void GuardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBotonActionPerformed
    archivo.guardar(this, areaPrincipal);
}//GEN-LAST:event_GuardarBotonActionPerformed

private void DeshacerBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeshacerBotonActionPerformed
    jsyntaxpane.actions.ActionUtils.sendKeyPress(areaPrincipal, KeyEvent.VK_Z, KeyEvent.CTRL_DOWN_MASK);

}//GEN-LAST:event_DeshacerBotonActionPerformed

private void CortarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CortarBotonActionPerformed
    areaPrincipal.cut();
}//GEN-LAST:event_CortarBotonActionPerformed

    private void NuevoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoBotonActionPerformed
        this.setTitle("Nuevo" );
        areaPrincipal.setText("");
        areaPrincipal.setFont(new Font("Arial",Font.PLAIN,14));
        archivo.nuevo();
    }//GEN-LAST:event_NuevoBotonActionPerformed

    private void GuardarComoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarComoBotonActionPerformed
        archivo.guardarComo(this, areaPrincipal);
    }//GEN-LAST:event_GuardarComoBotonActionPerformed

    private void CopiarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopiarBotonActionPerformed
        areaPrincipal.copy();
    }//GEN-LAST:event_CopiarBotonActionPerformed

    private void PegarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PegarBotonActionPerformed
        areaPrincipal.paste();
    }//GEN-LAST:event_PegarBotonActionPerformed

    private void SeleccionarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarBotonActionPerformed
        areaPrincipal.selectAll();
    }//GEN-LAST:event_SeleccionarBotonActionPerformed

    private void archivoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoGuardarActionPerformed
        archivo.guardar(this, areaPrincipal);      
    }//GEN-LAST:event_archivoGuardarActionPerformed

    private void archivoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoAbrirActionPerformed
        JTextArea texto = archivo.abrir(this);
        try {
            areaPrincipal.setText(texto.getText());
        } catch (Exception ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_archivoAbrirActionPerformed

    private void BuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBotonActionPerformed
        jsyntaxpane.actions.ActionUtils.sendKeyPress(areaPrincipal, KeyEvent.VK_F, KeyEvent.CTRL_DOWN_MASK);
    }//GEN-LAST:event_BuscarBotonActionPerformed

    private void tutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialActionPerformed
        Ayuda ayuda = new Ayuda();
        ayuda.setVisible(true);
        ayuda.setBounds(20, 20, 800, 500);
    }//GEN-LAST:event_tutorialActionPerformed

    private void acercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeActionPerformed
        AcercaDe acercade = new AcercaDe();
        acercade.setVisible(true);
        acercade.setBounds(20, 20, 250, 500);
    }//GEN-LAST:event_acercaDeActionPerformed

    private void EjecutarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarBotonActionPerformed
        try{
            lexicoAnalizador();
            Sintactico sintactico = new Sintactico(archivo.getName());
            sintactico.analizadorSintactico();
            arbolSintactico.setModel(sintactico.getTree());
            arbolSemantico.setModel(sintactico.getTreeSem());
//            System.out.println("hola");
            tablaPanel.setModel(sintactico.getTabla().getModel());
//            System.out.println("que hace");
//            Iterator sentencias = sintactico.getSentenciasRaiz().iterator();
           
//            Iterator sentencias = sintactico.getRaiz().getNodo().iterator();
//            while(sentencias.hasNext())
//                imprimeArbolConsola((Nodo)sentencias.next(),0);

//            CodigoP codigoP = new CodigoP(sintactico.getSentenciasRaiz());
//            codigoP.recorreArbol();
//            codigoP.muestraCodigoP();
//            codigoP.muestraCodigoPenArea(areaCodigoP);
            CodigoP codigo = new CodigoP(sintactico.getRaiz());
//            System.out.println("\nCodigo!!\n"+codigo.codigoIntermedio());
            codigo.muestraCodigoPenArea(areaCodigoP);

            ArrayList<String> as = sintactico.getErrores();
            Iterator e = as.iterator();
            String err="";
            while (e.hasNext()) {
                err = (String) e.next();
                errores.setText(errores.getText() + err);
                }
            if ("".equals(err)) {errores.append("Ningun Error Sintáctico detectado");}
            else {errores.append(err);}
            
        }catch(Exception e){
            
        }
                                         
    }//GEN-LAST:event_EjecutarBotonActionPerformed

    
    
    private void imprimeArbolConsola(Nodo raiz, int tab){
        for (int i = 0; i < tab; i++) 
            System.out.print("\t");
        System.out.println("Dato: {"+raiz.getDato()+ "}\tToken: {"+raiz.getToken()+"}\tTipo dato = "+raiz.getTipoDato());
//        if(raiz.getToken()==null)
//            System.out.println("estoy vacio mijo =(");
        ArrayList<Nodo> hijos = raiz.getNodo();
        Iterator hijosIterator = hijos.iterator();
        while (hijosIterator.hasNext()){
            imprimeArbolConsola((Nodo)hijosIterator.next(),tab+1);
        }
        
    }
    
    
    private void ReemplazarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReemplazarBotonActionPerformed
        jsyntaxpane.actions.ActionUtils.sendKeyPress(areaPrincipal, KeyEvent.VK_H, KeyEvent.CTRL_DOWN_MASK);
    }//GEN-LAST:event_ReemplazarBotonActionPerformed

    private void RehacerBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RehacerBotonActionPerformed
        jsyntaxpane.actions.ActionUtils.sendKeyPress(areaPrincipal, KeyEvent.VK_Y, KeyEvent.CTRL_DOWN_MASK);
    }//GEN-LAST:event_RehacerBotonActionPerformed

    private void archivoGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoGuardarComoActionPerformed
        archivo.guardarComo(this, areaPrincipal);
    }//GEN-LAST:event_archivoGuardarComoActionPerformed

    private void archivoCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoCerrarActionPerformed
        this.setTitle("Nuevo" );
        areaPrincipal.setText("");
        areaPrincipal.setFont(new Font("Arial",Font.PLAIN,14));
        archivo.nuevo();
    }//GEN-LAST:event_archivoCerrarActionPerformed

    private void archivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoSalirActionPerformed
        jsyntaxpane.actions.ActionUtils.sendKeyPress(areaPrincipal, KeyEvent.VK_F4, KeyEvent.ALT_DOWN_MASK);
    }//GEN-LAST:event_archivoSalirActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jsyntaxpane.actions.ActionUtils.sendKeyPress(areaPrincipal, KeyEvent.VK_Z, KeyEvent.CTRL_DOWN_MASK);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jsyntaxpane.actions.ActionUtils.sendKeyPress(areaPrincipal, KeyEvent.VK_Y, KeyEvent.CTRL_DOWN_MASK);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        areaPrincipal.cut();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        areaPrincipal.copy();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        areaPrincipal.paste();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        areaPrincipal.selectAll();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        jsyntaxpane.actions.ActionUtils.sendKeyPress(areaPrincipal, KeyEvent.VK_F, KeyEvent.CTRL_DOWN_MASK);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        jsyntaxpane.actions.ActionUtils.sendKeyPress(areaPrincipal, KeyEvent.VK_H, KeyEvent.CTRL_DOWN_MASK);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
//        lexicoAnalizador();
//        Sintactico sintactico = new Sintactico();
//        sintactico.analizadorSintactico();
//        Arbol.setModel(sintactico.getTree());
//        ArrayList<String> as = sintactico.getErrores();
//        Iterator e = as.iterator();
//        String err="";
//        while (e.hasNext()) {
//            err = (String) e.next();
//            errores.setText(errores.getText() + err);
//            }
//        if ("".equals(err)) {errores.append("Ningun Error Sintáctico detectado");}
//        else {errores.append(err);}
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
//        lexicoAnalizador();
//        Sintactico sintactico = new Sintactico();
//        sintactico.analizadorSintactico();
//        Arbol.setModel(sintactico.getTree());
//        ArrayList<String> as = sintactico.getErrores();
//        Iterator e = as.iterator();
//        String err="";
//        while (e.hasNext()) {
//            err = (String) e.next();
//            errores.setText(errores.getText() + err);
//            }
//        if ("".equals(err)) {errores.append("Ningun Error Sintáctico detectado");}
//        else {errores.append(err);}
    }//GEN-LAST:event_jMenuItem14ActionPerformed

        private void deleteComent(){
            String nuevo=null;
            nuevo = archivo.deleteComen(this, areaPrincipal);
            areaPrincipal.setText(nuevo);
        }
    
    private void lexicoAnalizador(){
        lex = true;
        deleteComent();
        String texto = areaPrincipal.getText();
        Lexico lexico = new Lexico(texto, archivo.getName());
        texto = lexico.obtenerCodigo();
        Alexico.setText(lexico.obtenerTokens());
        buscarRes.addIdentificador();
        errores.setText(lexico.getError());
        StringTokenizer tokens = new StringTokenizer(texto,"\n");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
            setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            }catch(Exception e){
            e.printStackTrace();
            }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Vista().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirBoton;
    private javax.swing.JTextArea Alexico;
    private javax.swing.JButton BuscarBoton;
    private javax.swing.JButton CompilarBoton;
    private javax.swing.JButton CopiarBoton;
    private javax.swing.JButton CortarBoton;
    private javax.swing.JButton DeshacerBoton;
    private javax.swing.JButton EjecutarBoton;
    private javax.swing.JButton GuardarBoton;
    private javax.swing.JButton GuardarComoBoton;
    private javax.swing.JMenu MArchivo;
    private javax.swing.JMenu MAyuda;
    private javax.swing.JMenu MCompilar;
    private javax.swing.JMenu MEdicion;
    private javax.swing.JButton NuevoBoton;
    private javax.swing.JButton PegarBoton;
    private javax.swing.JButton ReemplazarBoton;
    private javax.swing.JButton RehacerBoton;
    private javax.swing.JButton SeleccionarBoton;
    private javax.swing.JMenuItem acercaDe;
    private javax.swing.JTree arbolSemantico;
    private javax.swing.JTree arbolSintactico;
    private javax.swing.JMenuItem archivoAbrir;
    private javax.swing.JMenuItem archivoCerrar;
    private javax.swing.JMenuItem archivoGuardar;
    private javax.swing.JMenuItem archivoGuardarComo;
    private javax.swing.JMenuItem archivoSalir;
    private javax.swing.JTextArea areaCodigoP;
    private javax.swing.JEditorPane areaPrincipal;
    private javax.swing.JTextArea errores;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTabbedPane panelTab;
    private javax.swing.JTable tablaPanel;
    private javax.swing.JMenuItem tutorial;
    // End of variables declaration//GEN-END:variables
    NumeroLinea linea;
    Archivo archivo;
    BuscaReservadas buscarRes = new BuscaReservadas();
    boolean lex = false;
}
